use_default_settings: true

server:
  secret_key: "change-me-in-production"
  limiter: false
  image_proxy: false

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "en"

outgoing:
  request_timeout: 10.0

engines:
  - name: google
    engine: google
    disabled: false
  - name: bing
    engine: bing
    disabled: false
  - name: duckduckgo
    engine: duckduckgo
    disabled: false

ui:
  static_use_hash: true

enabled_plugins:
  - 'Hash plugin'
  - 'Self Informations'
